from enum import Enum


class Category(str, Enum):
    POLITICS_POLICY = "POLITICS_POLICY"
    ECONOMY_MARKETS = "ECONOMY_MARKETS"
    SCIENCE_TECH = "SCIENCE_TECH"
    SOCIETY_CULTURE = "SOCIETY_CULTURE"
    ENVIRONMENT_CLIMATE = "ENVIRONMENT_CLIMATE"
    CRIME_SAFETY = "CRIME_SAFETY"
    HEALTH = "HEALTH"
    UNCATEGORISED = "UNCATEGORISED"
